# Generated by Django 5.1.2 on 2024-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
